### PR TITLE
Add Facebook Community Guidelines

### PR DESCRIPTION
**Pull request by clementbiron**

### CODE REVIEW

**Comment by martinratinaud** [comment]
@clementbiron I hope they won't change it too often because I'm almost sure those react selectors will fail on next update

**Comment by clementbiron** [comment]
I hope too !

**Comment by MattiSG** [comment]
I agree. I noticed that in other cases you managed to have more stable ones. Do we have those here because of time pressure or is there no way to make them better?

In any case it will be interesting to measure how stable those are 🙂

**Comment by clementbiron** [comment]
I took the time to look for the most stable selectors I could find.

Let's see what's happen to the next update.

**Pull request merged**
